// ISO country list with dial codes. Flag emoji is derived from ISO code.
// Source: ITU-T E.164 + ISO 3166-1 alpha-2.

const toFlag = (iso) =>
    iso
        .toUpperCase()
        .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));

const RAW = [
    ["US", "United States", "1"],
    ["IN", "India", "91"],
    ["GB", "United Kingdom", "44"],
    ["CA", "Canada", "1"],
    ["AU", "Australia", "61"],
    ["AE", "United Arab Emirates", "971"],
    ["DE", "Germany", "49"],
    ["FR", "France", "33"],
    ["ES", "Spain", "34"],
    ["IT", "Italy", "39"],
    ["NL", "Netherlands", "31"],
    ["BR", "Brazil", "55"],
    ["MX", "Mexico", "52"],
    ["JP", "Japan", "81"],
    ["KR", "South Korea", "82"],
    ["CN", "China", "86"],
    ["SG", "Singapore", "65"],
    ["HK", "Hong Kong", "852"],
    ["ID", "Indonesia", "62"],
    ["MY", "Malaysia", "60"],
    ["PH", "Philippines", "63"],
    ["TH", "Thailand", "66"],
    ["VN", "Vietnam", "84"],
    ["PK", "Pakistan", "92"],
    ["BD", "Bangladesh", "880"],
    ["LK", "Sri Lanka", "94"],
    ["NP", "Nepal", "977"],
    ["SA", "Saudi Arabia", "966"],
    ["QA", "Qatar", "974"],
    ["KW", "Kuwait", "965"],
    ["OM", "Oman", "968"],
    ["BH", "Bahrain", "973"],
    ["IL", "Israel", "972"],
    ["TR", "Turkey", "90"],
    ["EG", "Egypt", "20"],
    ["ZA", "South Africa", "27"],
    ["NG", "Nigeria", "234"],
    ["KE", "Kenya", "254"],
    ["GH", "Ghana", "233"],
    ["TZ", "Tanzania", "255"],
    ["UG", "Uganda", "256"],
    ["AR", "Argentina", "54"],
    ["CL", "Chile", "56"],
    ["CO", "Colombia", "57"],
    ["PE", "Peru", "51"],
    ["VE", "Venezuela", "58"],
    ["RU", "Russia", "7"],
    ["UA", "Ukraine", "380"],
    ["PL", "Poland", "48"],
    ["RO", "Romania", "40"],
    ["CZ", "Czech Republic", "420"],
    ["AT", "Austria", "43"],
    ["CH", "Switzerland", "41"],
    ["BE", "Belgium", "32"],
    ["SE", "Sweden", "46"],
    ["NO", "Norway", "47"],
    ["DK", "Denmark", "45"],
    ["FI", "Finland", "358"],
    ["IE", "Ireland", "353"],
    ["PT", "Portugal", "351"],
    ["GR", "Greece", "30"],
    ["HU", "Hungary", "36"],
    ["SK", "Slovakia", "421"],
    ["BG", "Bulgaria", "359"],
    ["HR", "Croatia", "385"],
    ["RS", "Serbia", "381"],
    ["LT", "Lithuania", "370"],
    ["LV", "Latvia", "371"],
    ["EE", "Estonia", "372"],
    ["IS", "Iceland", "354"],
    ["LU", "Luxembourg", "352"],
    ["MT", "Malta", "356"],
    ["CY", "Cyprus", "357"],
    ["NZ", "New Zealand", "64"],
    ["TW", "Taiwan", "886"],
];

export const COUNTRIES = RAW.map(([iso, name, dial]) => ({
    iso,
    name,
    dial,
    flag: toFlag(iso),
})).sort((a, b) => a.name.localeCompare(b.name));

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.iso === "CA") || COUNTRIES[0];
